learning_templates/basicapp/urls.py
from django.urls import path, re_path
from basicapp import views

# template taggihg

app_name ='basicapp'

urlpatterns = [
    re_path(r'^relative/$',views.relative, name='relative'),
    re_path(r'^other/$', views.other, name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls')),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')
    
def other(request):
    mydict = {'name': 'Harshwardhan', 'Mob':9970544367}
    return render(request,'basicapp/other.html',mydict)

def relative(request):
    return render(request,'basicapp/relative_url.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basicapp:other' %}">Other</a>
      </div>
    </nav>
    {% block content %}

{% endblock  %}
</body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My title</title>
    <link rel="stylesheet" type="text/css" href="theme.css">
  </head>
  <body>
    <h1> This is index file</h1>	
    <h1><a href = "{% url 'basicapp:other' %}">Other Link</a></h1>
  </body>
</html>

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>

    {% extends 'basicapp/base.html' %}
    {% block content %}
    <h1> Welcome To Other</h1>	
    <h1>{{Mob | Mob}}</h1>
    {% endblock  %}

learning_templates/templates/basicapp/relative_url.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My title</title>
    <link rel="stylesheet" type="text/css" href="theme.css">
  </head>
  <body>
    <h1> Welcome to relative url Templates</h1>	
    <a href="{% url 'basicapp:other' %}" >The Other Page </a>
    <p><a href="{% url 'admin:index' %}">ADMIN</a></p>
    <p><a href="{% url 'index' %}">INDEX PAGE</a></p>

  </body>
</html>